name: backscreen_generator
description: 自己紹介を書いたバーチャル背景画像を簡単に作れます！

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  reactive_forms: ^11.0.1
  flutter_hooks: ^0.18.2+1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  url_launcher: ^6.0.20
  url_launcher_web: ^2.0.8
  flutter_linkify: ^5.0.2
  universal_html:
  cupertino_icons: ^1.0.4
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

linter:
  exclude:
    - "*.g.dart"
    - "*.freezed.dart"

flutter:
  uses-material-design: true
  fonts:
      - family: Noto Sans JP
        fonts:
          - asset: assets/fonts/NotoSansJP-Regular.otf