name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@master
        with:
          channel: master
      - name: Build App
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BACKSCREEN_GENERATOR }}'
          channelId: live
          projectId: backscreen-generator
